version: '3'

services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
          - POSTGRES_USER=${DATABASE_USER}
          - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
          - POSTGRES_DB=${DATABASE_NAME}
          - POSTGRES_HOST=${DATABASE_HOST}
          - POSTGRES_PORT=${DATABASE_PORT}
        ports:
          - ${DATABASE_PORT}
        volumes:
          - pgdata:/var/lib/postgresql/data

    duplo_api:
        container_name: backend
        build: ./
        command: >
            bash -c "npm install 
            && npm start"
        working_dir: /usr/src/duplo_api
        environment:
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_DIALECT=${DATABASE_DIALECT}
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_LOGGING=${DATABASE_LOGGING}
            - DATABASE_MIN=${DATABASE_MIN}
            - DATABASE_MAX=${DATABASE_MAX}
            - DATABASE_IDLE=${DATABASE_IDLE}
            - DATABASE_ACQUIRE=${DATABASE_ACQUIRE}
            - DATABASE_TIMESTAMPS=${DATABASE_TIMESTAMPS}
            - JWTSECRET=${JWTSECRET}
            - JWTEXPIRESIN=${JWTEXPIRESIN}
            - SENDGRID_API_KEY=${SENDGRID_API_KEY}
        links:
            - postgres
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./:/usr/src/duplo_api
volumes:
    pgdata: