swagger: '2.0'
info:
  version: '1.0'
  title: DUPLO-ASSESSMENT-API
  description: 'TODO: Add Description'
  contact: {}
host: ''
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: ''
      summary: BASE
      operationId: UnnammedEndpointGet
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        200:
          description: ''
          headers: {}
